# File: config/app_config.yaml
# DocuGen Application Configuration

logging:
  level: INFO
  file_pattern: "logs/docugen_{date}.log"
  console_output: true

paths:
  templates_dir: "templates"
  output_dir: "output"
  data_dir: "data"

output:
  formats: ["docx", "pdf"]
  naming_pattern: "{ACN}_{LastName}"
  duplicate_handling: "rename" # rename, overwrite, skip
  directory_structure: "flat" # flat or organized

pdf:
  primary_converter: "docx2pdf"
  fallback_converter: "libreoffice"
  export_format: "pdf:writer_pdf_Export:SelectPdfVersion=1"
  headless_mode: true
  skip_word_open: true

processing:
  batch_size: 100
  progress_save_interval: 10
  continue_on_errors: true
  parallel_workers: 1 # Phase 1: sequential only

validation:
  strict_mode: false
  log_warnings: true
  required_fields_enforce: false

input:
  client_map: "/Users/byron/repos/DATABASE/chsp_client_mapper/output/chsp_client_map.json"

sharepoint:
  tenant_name: "nationalabilitycare"  # From .env SHAREPOINT_SITE_URL
  site_name: "Caura2"                 # From .env SHAREPOINT_SITE_URL
  full_site_url: "https://nationalabilitycare.sharepoint.com/sites/Caura2"  # Fallback
  document_library: "Documents"       # Document library name
  base_folder: "CHSP/Clients/Client Records"  # Base folder for care plans
  folder_structure: "CarePlans/{acn}-{given_name}-{family_name}"

# Microsoft Graph API credentials (loaded from config/.env)
graph_api:
  client_id: "${AZURE_CLIENT_ID}"     # From .env
  client_secret: "${AZURE_CLIENT_SECRET}"  # From .env  
  tenant_id: "${AZURE_TENANT_ID}"     # From .env
